### ISSUE TITLE
Warning: already initialized constant VERSION

### ISSUE THREAD

**Issue by diegosteiner** [renuo/isbn#1]
I'm keep getting the following warning during deployment:

``` bash
/var/www/app/vendor/bundle/ruby/1.9.1/bundler/gems/isbn-3373a99856d5/lib/isbn.rb:4: 

warning: already initialized constant VERSION
```

**Comment by lukaselmer** [comment]
Then fix it ;-) you shuold have access
Am 01.12.2012 09:29 schrieb "Diego Steiner" notifications@github.com:

**Comment by lukaselmer** [comment]
Fixed it

2012/12/1 Lukas Elmer lukas.elmer@gmail.com

**Comment by lukaselmer** [comment]
Cleanup :-)
